language: ruby
rvm:
- 2.3.3
before_install:
- openssl aes-256-cbc -K $encrypted_bd09cc9bac76_key -iv $encrypted_bd09cc9bac76_iv -in deploy_rsa.enc -out deploy_rsa -d
install:
- sudo apt-get update
- sudo apt-get install sshpass
- bundle install
script: jekyll build
after_success:
# - sshpass -p $ftpPassword rsync -Cravzp /home/travis/build/gruponews/jekyll-teste/_site/*
#   gruponewscombr@gruponews.com.br:~/jekyll.gruponews.com.br/public

addons:
  ssh_known_hosts: gruponews.com.br

before_deploy:
- openssl aes-256-cbc -K  $encrypted_bd09cc9bac76_key -iv $encrypted_bd09cc9bac76_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -Cravzp $TRAVIS_BUILD_DIR/_site/* gruponewscombr@gruponews.com.br:~/jekyll.gruponews.com.br/public
