language: ruby
rvm:
  - 2.3.3
install:
  - sudo apt-get update
  - sudo apt-get install sshpass
  - bundle install
script: jekyll build
after_success:
  - sshpass -p $ftpPassword scp -r /home/travis/build/gruponews/jekyll-teste/_site/* gruponewscombr@gruponews.com.br:jekyll.gruponews.com.br/public
  - echo 'Teste OK'
