language: ruby
rvm:
  - 2.3.3
install: bundle install
script: jekyll build
after_success: "curl --ftp-create-dirs -T /home/travis/build/gruponews/jekyll-teste/_site/* -u $ftpUser:$ftpPassword ftp://$ftpAddress/$ftpDir"
